build:
  cuda_version: "12.1.1"
  python_version: "3.10"
  system_packages:
    - "git"
    - "ffmpeg"
  python_packages:
    - "inferless-cli==2.0.9"
    - "torch"
    - "ninja"
    - "pydantic"
    - "accelerate>=1.1.1"
    - "xformers"
    - "tqdm"
    - "easydict"
    - "omegaconf"
    - "diffusers==0.30.1"
    - "transformers==4.51.3"
    - "tokenizers>=0.20.3"
    - "safetensors"
    - "datasets"
    - "Pillow"
    - "opencv-python>=4.9.0.80"
    - "decord"
    - "scikit-image"
    - "albumentations"
    - "imageio"
    - "imageio-ffmpeg"
    - "moviepy==1.0.3"
    - "pyav" 
    - "librosa"
    - "einops"
    - "timm"
    - "tomesd"
    - "torchdiffeq"
    - "torchsde"
    - "numpy>=1.23.5,<2"
    - "ftfy"
    - "sentencepiece"
    - "beautifulsoup4"
    - "protobuf"
    - "watchdog"
    - "websockets"
    - "tensorboard"
    - "gradio>=5.0.0"
    - "dashscope"

  run:
    - "git clone https://huggingface.co/spaces/dangthr/StableAvatar"
