build:
  cuda_version: "12.1.1"
  python_version: "3.10"
  system_packages:
    - "git"
    - "ffmpeg"
  python_packages:
    - "gradio>=5.0.0"

  run:
    - "git clone https://huggingface.co/spaces/dangthr/StableAvatar && cd StableAvatar && pip install -r requirements.txt && python downloader.py"
